'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Hero from "@/components/heroSection"
import { Provider } from "react-redux";
import {store} from '../ReduxStore/Store'
import MainSection from "@/components/main";
import SmallScreenHeader from "@/components/smallScreenHeader";
import FooterSmallScreen from "@/components/footerSmallScreen";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        
        <Provider store={store}>
        <Header/>
        <SmallScreenHeader/>
        <Hero/>
        <MainSection>{children}</MainSection>
        <FooterSmallScreen/>
          {/* {children} */}
          </Provider>
      
      </body>
    </html>
  );
}
